<script lang="ts">
	import SeoHead from '$lib/components/SeoHead.svelte';

	export const prerender = true;

	// NOTE (for the operator): technical draft aligned to current behavior; not legal
	// advice. Have counsel review before launch.
	const effectiveDate = 'July 18, 2026';
	const contactEmail = 'support@taxnexusapp.com';
</script>

<SeoHead
	pageTitle="Terms of Service"
	description="The terms governing access to and use of TaxNexus — subscriptions, refunds, disclaimers, and the informational-only nature of the software."
/>

<article class="prose prose-sm mx-auto max-w-3xl px-4 py-10">
	<h1>Terms of Service</h1>
	<p><em>Effective date: {effectiveDate}</em></p>

	<p>
		These Terms of Service (“Terms”) govern your access to and use of TaxNexus (the “Service”), operated
		by <strong>Consult Solutions</strong>, an Oakland, California company (“TaxNexus”, “we”, “us”). By
		creating an account or using the Service, you agree to these Terms. If you do not agree, do not use
		the Service.
	</p>

	<h2>1. What TaxNexus is (and is not)</h2>
	<p>
		TaxNexus is compliance monitoring <strong>software</strong>. It helps e-commerce sellers track their
		sales activity against California tax nexus thresholds — including the California Department of Tax
		and Fee Administration (CDTFA) economic nexus threshold for sales and use tax and the Franchise Tax
		Board (FTB) “doing business” thresholds for franchise and income tax — and flags potential
		physical-presence nexus, such as inventory stored in California fulfillment centers.
	</p>
	<p>
		<strong>
			TaxNexus provides informational tools only and does not constitute tax, legal, or financial
			advice. Users should consult a qualified tax professional for their specific filing obligations.
		</strong>
		Outputs from the Service — including nexus risk assessments, penalty estimates, filing checklists,
		and chatbot responses — are estimates generated by software based on the data you provide and
		publicly available threshold information. They may be incomplete, out of date, or inapplicable to
		your specific circumstances.
	</p>
	<p>
		Use of the Service does not create an accountant-client, attorney-client, or any other professional
		relationship. You should consult a qualified tax professional before making decisions about
		registration, filing, or payment of any tax.
	</p>

	<h2>2. Eligibility and accounts</h2>
	<p>
		You must be at least 18 years old and able to form a binding contract to use the Service. You are
		responsible for maintaining the confidentiality of your account credentials and for all activity
		under your account. You agree to provide accurate account information and to keep it current.
	</p>

	<h2>3. Subscriptions, trials, and billing</h2>
	<p>
		The Service is offered as a subscription with the plans and pricing listed at
		<a href="/pricing">taxnexusapp.com/pricing</a>.
	</p>
	<ul>
		<li>
			<strong>Free trial.</strong> New accounts may receive a 14-day free trial. No payment method is
			required to start a trial. At the end of the trial, continued access requires an active paid
			subscription.
		</li>
		<li>
			<strong>Billing.</strong> Subscriptions are billed in advance on a recurring monthly basis and
			renew automatically until cancelled. Depending on your location, payment is processed by
			<strong>Stripe</strong> or by <strong>Lemon Squeezy</strong> acting as merchant of record. Where
			Lemon Squeezy is the merchant of record, your purchase is also subject to Lemon Squeezy’s terms of
			sale. Prices shown in-app are indicative; the exact amount and currency are confirmed at checkout.
		</li>
		<li>
			<strong>Cancellation.</strong> You may cancel at any time from your account settings. Cancellation
			takes effect at the end of the current billing period, and you retain access until then.
		</li>
		<li>
			<strong>Price changes.</strong> We may change subscription pricing with at least 30 days’ notice.
			Changes apply at your next renewal.
		</li>
		<li>
			<strong>Refunds.</strong> Refunds are governed by our <a href="/refunds">Refund Policy</a>.
		</li>
	</ul>

	<h2>4. Your data and responsibilities</h2>
	<p>
		The accuracy of the Service’s outputs depends on the accuracy and completeness of the sales,
		inventory, and business data you provide or connect. You are solely responsible for:
	</p>
	<ul>
		<li>the accuracy of the data you supply;</li>
		<li>verifying any output before relying on it;</li>
		<li>your own tax registration, collection, filing, and payment obligations; and</li>
		<li>compliance with applicable laws in your use of the Service.</li>
	</ul>

	<h2>5. Acceptable use</h2>
	<p>
		You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to gain unauthorized
		access to the Service or its systems; (c) reverse engineer, scrape, or copy the Service except as
		permitted by law; (d) resell or sublicense the Service without our written consent; (e) interfere
		with the operation or security of the Service; or (f) use the Service to develop a competing
		product.
	</p>

	<h2>6. Intellectual property</h2>
	<p>
		The Service, including its software, design, content, and trademarks, is owned by Consult Solutions
		and protected by intellectual property laws. We grant you a limited, non-exclusive,
		non-transferable, revocable license to use the Service for your internal business purposes during
		your subscription. You retain all rights to the data you submit; you grant us a limited license to
		process that data solely to provide and improve the Service.
	</p>

	<h2>7. Third-party services</h2>
	<p>
		The Service integrates with or relies on third-party services (for example, payment processors,
		hosting providers, email delivery, and AI model providers used to power in-app assistance). We are
		not responsible for third-party services, and your use of them may be subject to their own terms.
	</p>

	<h2>8. Disclaimers</h2>
	<p>
		THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
		IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT,
		ACCURACY, OR THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. WITHOUT LIMITING THE FOREGOING, WE
		DO NOT WARRANT THAT ANY NEXUS ASSESSMENT, THRESHOLD CALCULATION, PENALTY ESTIMATE, OR OTHER OUTPUT IS
		ACCURATE, COMPLETE, OR CURRENT, OR THAT USE OF THE SERVICE WILL SATISFY ANY TAX OBLIGATION.
	</p>
	<p>
		Tax laws and thresholds change. Indexed thresholds are updated by government agencies on their own
		schedules, and there may be delays before such changes are reflected in the Service.
	</p>

	<h2>9. Limitation of liability</h2>
	<p>
		TO THE MAXIMUM EXTENT PERMITTED BY LAW, CONSULT SOLUTIONS WILL NOT BE LIABLE FOR ANY INDIRECT,
		INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY TAXES, PENALTIES, INTEREST, OR
		ASSESSMENTS IMPOSED BY ANY TAX AUTHORITY, OR FOR LOST PROFITS, REVENUE, OR DATA, ARISING FROM OR
		RELATED TO YOUR USE OF THE SERVICE. OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF THESE
		TERMS OR THE SERVICE WILL NOT EXCEED THE AMOUNTS YOU PAID US FOR THE SERVICE IN THE TWELVE (12)
		MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM.
	</p>
	<p>Some jurisdictions do not allow certain limitations, so some of the above may not apply to you.</p>

	<h2>10. Indemnification</h2>
	<p>
		You agree to indemnify and hold harmless Consult Solutions from claims, damages, and expenses
		(including reasonable attorneys’ fees) arising from your data, your use of the Service, or your
		violation of these Terms.
	</p>

	<h2>11. Termination</h2>
	<p>
		We may suspend or terminate your access to the Service for violation of these Terms or for
		non-payment. You may stop using the Service and cancel your subscription at any time. Sections that
		by their nature should survive termination (including Sections 6, 8, 9, and 10) will survive.
	</p>

	<h2>12. Changes to these Terms</h2>
	<p>
		We may update these Terms from time to time. If changes are material, we will provide notice (for
		example, by email or in-app notice) at least 14 days before they take effect. Continued use of the
		Service after the effective date constitutes acceptance.
	</p>

	<h2>13. Governing law and disputes</h2>
	<p>
		These Terms are governed by the laws of the State of California, without regard to conflict-of-law
		principles. Any dispute will be resolved in the state or federal courts located in Alameda County,
		California, and you consent to their jurisdiction.
	</p>

	<h2>14. Contact</h2>
	<p>Questions about these Terms: <a href={'mailto:' + contactEmail}>{contactEmail}</a>.</p>
	<p>Consult Solutions — Oakland, California.</p>
</article>
